server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - CountRequestsFilter
        - LogFilter
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: oauth-service
          uri: lb://oauth-service
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

config:
  security:
    oauth:
      client:
        id: backend-specialization
        secret: backend-dh
      jwt:
        key: it-s-dangerous-to-go-alone-take-this