server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - CountRequestsFilter
        - LogFilter
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
