server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - CountRequestsFilter
        - LogFilter
      routes:
        - id: animal-service
          uri: lb://animal-service
          predicates:
            - Path=/animals/**
        - id: specie-service
          uri: lb://specie-service
          predicates:
            - Path=/species/**
